### ISSUE TITLE
Compilation hangs on 64-bit `checked_mul` call

### ISSUE THREAD

**Issue by mrk-its** [mrk-its/rust-mos#10]
Compilation of following code (`cargo build`) hangs:

`src/main.rs`:
```rust

#![no_std]
#![feature(start)]
#![allow(unused_variables)]

use core::panic::PanicInfo;
use ufmt_stdio::*;

#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    loop {}
}

#[start]
fn main(_argc: isize, _argv: *const *const u8) -> isize {
    let mut result: u64 = 10;
    for _ in 0..3 {
        result = result.checked_mul(10).unwrap_or(0);
        println!("result: {}", result);
    }
    0
}

```

`.cargo/config.toml`:
```toml
[build]
target = "mos-sim-none"

[target.mos-sim-none]
runner = ["mos-sim", "--cycles"]

[unstable]
build-std = ["core"]
```

`Cargo.toml`:
```toml
[package]
name = "hang"
version = "0.1.0"
edition = "2021"

[profile.dev]
lto = true
opt-level = "s"
panic = "abort"
overflow-checks = true

[dependencies]
ufmt-stdio = "0"

```
